[package]
name = "tvpilot"
version = "0.1.0"
edition = "2024"

[dependencies]
dbus = "0.9"
dbus-tokio = "0.7"
tokio = { version = "1", features = ["macros", "rt", "io-util", "net", "time"] }
futures = { version = "0.3", default-features = false, features = ["std", "async-await"] }
serde = { version = "1", features = ["derive"] }
postcard = { version = "1", features = ["alloc"] }
anyhow = "1"
libc = "0.2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
